http://localhost:8080/api/app/news

####
POST http://localhost:8080/api/app/news/like/1

###
POST http://localhost:8080/api/app/news
Content-type: application/json

{
 "author": "Fetta",
 "category": "Dev",
 "content": "formation Angular",
 "likes": 100   
}

###
http://localhost:8080/data/books.json

###
http://localhost:4200/data/books.json

